export const GAME_CONFIG = {
  width: 1280,
  height: 720,
  backgroundGrid: 40,
  formation: {
    rows: 2,
    columns: 10,
    lateralSpacing: 38,
    rankSpacing: 30,
    playerMoveSpeed: 96,
    soldierCatchupSpeed: 300,
    arenaMarginX: 180,
    arenaMarginY: 205,
  },
  reform: {
    soldierCatchupSpeed: 345,
    settleDistance: 5,
    reloadPenalty: 0.75,
    breakOffReloadPenalty: 1.15,
    breakOffDistance: 125,
  },
  soldier: {
    maxHp: 100,
    radius: 9,
    bodyLength: 20,
    bodyWidth: 12,
  },
  musket: {
    damage: 100,
    reloadSeconds: 3.6,
    enemyReloadSeconds: 4.0,
    projectileSpeed: 1040,
    projectileLife: 1.2,
    spreadRadians: 0.095,
    muzzleOffset: 17,
    bulletRadius: 3,
    effectiveRange: 610,
    enemyStopRange: 520,
    enemyRetreatRange: 330,
    enemyMoveSpeed: 54,
    enemyRetreatSpeed: 40,
    defensiveVolleyRange: 360,
  },
  charge: {
    maxDistance: 360,
    moveSpeed: 245,
    contactDistance: 42,
    stopDistance: 10,
    postChargeReloadPenalty: 1.2,
    arrowMinDistance: 36,
    enemyChargeMinDistance: 170,
    enemyChargeMaxDistance: 330,
    enemyDecisionInterval: 0.75,
    enemyChargeChance: 0.34,
  },
  melee: {
    moveSpeed: 104,
    acquireRange: 150,
    attackRange: 28,
    attackDamage: 34,
    attackCooldown: 0.72,
    attackWindup: 0.12,
    separationRadius: 22,
    separationStrength: 58,
    knockbackSpeed: 72,
    knockbackDamping: 0.055,
    arenaPadding: 20,
    disengageDistance: 175,
    disengageDelay: 1.35,
  },
  effects: {
    smokeLifetime: 1.05,
    flashLifetime: 0.09,
    corpseLifetime: 3.2,
    screenShake: 6.5,
    chargeShake: 3.2,
    meleeShake: 2.3,
    meleeStrikeLifetime: 0.12,
  },
} as const;
