export const GAME_CONFIG = {
  width: 960,
  height: 540,
  backgroundGrid: 32,
  player: {
    maxHp: 100,
    moveSpeed: 150,
    radius: 16,
    attackRange: 50,
    attackAngleDeg: 90,
    damage: 20,
    attackCooldown: 0.8,
    regenPerSecond: 4,
    regenDelay: 2.0,
    respawnDelay: 2.0,
  },
  ai: {
    maxHp: 100,
    moveSpeed: 100,
    radius: 16,
    attackRange: 50,
    attackAngleDeg: 90,
    damage: 20,
    attackCooldown: 0.8,
    regenPerSecond: 3,
    regenDelay: 2.0,
    respawnDelay: 2.0,
  },
} as const;
